version: 2
jobs:
  build:
    working_directory: ~/playground
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: playground-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: playground-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run: yarn test -- --no-watch --no-progress --browsers=ChromeHeadless
      # - run: npm run e2e -- --protractor-config=e2e/protractor.conf.js